query PanelTelegramConfig {
	panelTelegramConfig {
		statusChangeNotification
		statusChangeChatId
		id
		botToken
		balanceThreshold
		balanceNotification
		balanceChatId
		productPricesUpdatedNotification
		productPricesUpdatedChatId
	}
}
